config/routes.rb
Rails.application.routes.draw do
  resources :pins
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:name, :photo, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
    <div class="container">
    <h1 class="display-4">Mi Pinterest</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to
        featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>
</div>
<div class="container">
<div class="titulo">
    <h1 class="display-5">Bienvenida</h1>
    <h3 style="color:darkkhaki">Intro Ruby on Rails</h3>
</div>
    <div class="row">
        <div class="col-md-4">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis praesentium deleniti aspernatur
                exercitationem dignissimos. Totam, non? Adipisci iste sit iusto possimus, consectetur corporis rem
                facilis dolor itaque officiis architecto alias! Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Inventore nobis quos facere tempora, laborum consequatur officiis doloremque debitis harum
                exercitationem iusto magni nihil in? Facilis nihil dolorum aperiam inventore cum. Lorem ipsum, dolor sit
                amet consectetur adipisicing elit. Omnis necessitatibus, dolores dolor quos eos placeat, nostrum earum
                adipisci alias perspiciatis consectetur dolorem cupiditate corrupti? Neque tenetur optio debitis quos
                repellendus?</p>
        </div>
        <div class="col-md-4">
            <p>LLorem ipsum dolor sit amet consectetur adipisicing elit. Omnis praesentium deleniti aspernatur
                exercitationem dignissimos. Totam, non? Adipisci iste sit iusto possimus, consectetur corporis rem
                facilis dolor itaque officiis architecto alias! Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Inventore nobis quos facere tempora, laborum consequatur officiis doloremque debitis harum
                exercitationem iusto magni nihil in? Facilis nihil dolorum aperiam inventore cum. Lorem ipsum, dolor sit
                amet consectetur adipisicing elit. Omnis necessitatibus, dolores dolor quos eos placeat, nostrum earum
                adipisci alias perspiciatis consectetur dolorem cupiditate corrupti? Neque tenetur optio debitis quos
                repellendus?</p>
        </div>
        <div class="col-md-4">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis praesentium deleniti aspernatur
                exercitationem dignissimos. Totam, non? Adipisci iste sit iusto possimus, consectetur corporis rem
                facilis dolor itaque officiis architecto alias! Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Inventore nobis quos facere tempora, laborum consequatur officiis doloremque debitis harum
                exercitationem iusto magni nihil in? Facilis nihil dolorum aperiam inventore cum. Lorem ipsum, dolor sit
                amet consectetur adipisicing elit. Omnis necessitatibus, dolores dolor quos eos placeat, nostrum earum
                adipisci alias perspiciatis consectetur dolorem cupiditate corrupti? Neque tenetur optio debitis quos
                repellendus?</p>
        </div>
        <div class="col3">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis praesentium deleniti aspernatur
                exercitationem dignissimos. Totam, non? Adipisci iste sit iusto possimus, consectetur corporis rem
                facilis dolor itaque officiis architecto alias! Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Inventore nobis quos facere tempora, laborum consequatur officiis doloremque debitis harum
                exercitationem iusto magni nihil in? Facilis nihil dolorum aperiam inventore cum. Lorem ipsum, dolor sit
                amet consectetur adipisicing elit. Omnis necessitatibus, dolores dolor quos eos placeat, nostrum earum
                adipisci alias perspiciatis consectetur dolorem cupiditate corrupti? Neque tenetur optio debitis quos
                repellendus?</p>
        </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>IntroduccionRorFinal</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="<%=home_index_path %>"><img alt="website Logo"
        src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Overwatch_circle_logo.svg/600px-Overwatch_circle_logo.svg.png"/
        style="width: 30px"> Mi Pinterest
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%=home_index_path %>">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=pins_path %>">Lista de Juegos</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      
      
      <form class="form-inline my-2 my-lg-0">
          <img alt="website Logo"
          src="https://images.vexels.com/media/users/3/135247/isolated/preview/e70a6296c2a79dc7a56ab05b103f38e8-signo-de-usuario-con-fondo-by-vexels.png"/
          style="width: 54px">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
  <%= yield %>
</body>

</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin, local: true) do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1 style="color:darkkhaki">Lista de Juegos</h1>
</br>

  <% @pins.each do |pin| %>

  <div class="col-md-4">
    <div class="thumbnail">
      <%= pin.name %>
      <%= image_tag(pin.photo, :style => 'width:300px') %>
      <%= pin.description %></br>
      <%= link_to 'Show', pin, :class => 'btn' %>
      <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
      <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
    </div>
  </div>
  <% end %>

  <br>
  <%= link_to 'New Pin', new_pin_path %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pin.name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@pin.photo, :style => 'width:300px') %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>